use super::*;
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use utils::ext::*;

const SLOT_DIR: &str = "sd:/ultimate";
const SLOT_FILE: &str = "OnAttackSlots.toml";
const SLOT_FILE_HEADER: &str = "\
# Generated by HDR's on_attack vtable scan hooks.
# Each table records the first observed fighter kind for a skyline on_attack offset.

";

const ON_ATTACK_OFFSET_COUNT: usize = 61;
const FIGHTER_KIND_SLOT_COUNT: usize = 0x78;
const FIGHTER_KIND_WORD_COUNT: usize = (FIGHTER_KIND_SLOT_COUNT + 63) / 64;

struct SlotCache {
    initialized: bool,
    bits: [[u64; FIGHTER_KIND_WORD_COUNT]; ON_ATTACK_OFFSET_COUNT],
}

static SLOT_CACHE: Mutex<SlotCache> = Mutex::new(SlotCache {
    initialized: false,
    bits: [[0; FIGHTER_KIND_WORD_COUNT]; ON_ATTACK_OFFSET_COUNT],
});

macro_rules! define_on_attack_log_hooks {
    ($(($slot:expr, $hook:ident, $offset:expr)),+ $(,)?) => {
        const ON_ATTACK_OFFSETS: [usize; ON_ATTACK_OFFSET_COUNT] = [$($offset),+];

        $(
            #[skyline::hook(offset = $offset)]
            pub unsafe extern "C" fn $hook(
                vtable: u64,
                battleObject: *mut BattleObject,
                collisionLog: CollisionLog,
            ) -> u64 {
                log_on_attack_slot($slot, $offset, vtable, battleObject);
                call_original!(vtable, battleObject, collisionLog)
            }
        )+
    };
}

define_on_attack_log_hooks! {
    (0, on_attack_log_68d7e0, 0x68d7e0),
    (1, on_attack_log_81ec30, 0x81ec30),
    (2, on_attack_log_854520, 0x854520),
    (3, on_attack_log_892af0, 0x892af0),
    (4, on_attack_log_8b8b90, 0x8b8b90),
    (5, on_attack_log_8dc4f0, 0x8dc4f0),
    (6, on_attack_log_90d630, 0x90d630),
    (7, on_attack_log_932f50, 0x932f50),
    (8, on_attack_log_9567c0, 0x9567c0),
    (9, on_attack_log_9720a0, 0x9720a0),
    (10, on_attack_log_994480, 0x994480),
    (11, on_attack_log_9a5070, 0x9a5070),
    (12, on_attack_log_9df7b0, 0x9df7b0),
    (13, on_attack_log_a0cec0, 0xa0cec0),
    (14, on_attack_log_a29ab0, 0xa29ab0),
    (15, on_attack_log_a47bf0, 0xa47bf0),
    (16, on_attack_log_a64ce0, 0xa64ce0),
    (17, on_attack_log_a82660, 0xa82660),
    (18, on_attack_log_aa6540, 0xaa6540),
    (19, on_attack_log_ab9970, 0xab9970),
    (20, on_attack_log_adb1a0, 0xadb1a0),
    (21, on_attack_log_af9350, 0xaf9350),
    (22, on_attack_log_b33d30, 0xb33d30),
    (23, on_attack_log_b5e240, 0xb5e240),
    (24, on_attack_log_b98cf0, 0xb98cf0),
    (25, on_attack_log_c08430, 0xc08430),
    (26, on_attack_log_c29220, 0xc29220),
    (27, on_attack_log_c456a0, 0xc456a0),
    (28, on_attack_log_c73580, 0xc73580),
    (29, on_attack_log_ca13a0, 0xca13a0),
    (30, on_attack_log_cd9ea0, 0xcd9ea0),
    (31, on_attack_log_cea640, 0xcea640),
    (32, on_attack_log_d13020, 0xd13020),
    (33, on_attack_log_d29f90, 0xd29f90),
    (34, on_attack_log_d575b0, 0xd575b0),
    (35, on_attack_log_d9aa90, 0xd9aa90),
    (36, on_attack_log_df0370, 0xdf0370),
    (37, on_attack_log_e2a690, 0xe2a690),
    (38, on_attack_log_e60c30, 0xe60c30),
    (39, on_attack_log_f96420, 0xf96420),
    (40, on_attack_log_f0acc0, 0xf0acc0),
    (41, on_attack_log_f2ae00, 0xf2ae00),
    (42, on_attack_log_f6f210, 0xf6f210),
    (43, on_attack_log_f93df0, 0xf93df0),
    (44, on_attack_log_fdf990, 0xfdf990),
    (45, on_attack_log_1006730, 0x1006730),
    (46, on_attack_log_1044590, 0x1044590),
    (47, on_attack_log_105cf60, 0x105cf60),
    (48, on_attack_log_10bbd90, 0x10bbd90),
    (49, on_attack_log_10d6ca0, 0x10d6ca0),
    (50, on_attack_log_1121600, 0x1121600),
    (51, on_attack_log_116dbb0, 0x116dbb0),
    (52, on_attack_log_1195670, 0x1195670),
    (53, on_attack_log_11d5a00, 0x11d5a00),
    (54, on_attack_log_11f5380, 0x11f5380),
    (55, on_attack_log_122a360, 0x122a360),
    (56, on_attack_log_12689c0, 0x12689c0),
    (57, on_attack_log_1287320, 0x1287320),
    (58, on_attack_log_12ae760, 0x12ae760),
    (59, on_attack_log_12dc040, 0x12dc040),
    (60, on_attack_log_130eff0, 0x130eff0),
}

#[derive(Clone, Copy)]
struct FighterName {
    kind_name: &'static str,
    fighter: &'static str,
}

fn slot_path() -> PathBuf {
    Path::new(SLOT_DIR).join(SLOT_FILE)
}

fn ensure_slot_file_exists() -> io::Result<()> {
    fs::create_dir_all(SLOT_DIR)?;

    let path = slot_path();
    if !path.exists() {
        fs::write(&path, SLOT_FILE_HEADER)?;
    }

    Ok(())
}

fn with_slot_cache<R>(f: impl FnOnce(&mut SlotCache) -> R) -> R {
    let mut guard = match SLOT_CACHE.lock() {
        Ok(guard) => guard,
        Err(err) => err.into_inner(),
    };
    f(&mut guard)
}

fn offset_slot(offset: usize) -> Option<usize> {
    ON_ATTACK_OFFSETS.iter().position(|known_offset| *known_offset == offset)
}

fn fighter_kind_bit(kind: i32) -> Option<(usize, u64)> {
    if kind < 0 {
        return None;
    }

    let kind = kind as usize;
    if kind >= FIGHTER_KIND_SLOT_COUNT {
        return None;
    }

    Some((kind / 64, 1u64 << (kind % 64)))
}

fn set_slot_bit(bits: &mut [[u64; FIGHTER_KIND_WORD_COUNT]; ON_ATTACK_OFFSET_COUNT], offset: usize, kind: i32) {
    if let (Some(slot), Some((word, mask))) = (offset_slot(offset), fighter_kind_bit(kind)) {
        bits[slot][word] |= mask;
    }
}

fn parse_toml_u64(value: &str) -> Option<u64> {
    let mut value = value.split('#').next().unwrap_or(value).trim();
    if value.starts_with('"') && value.ends_with('"') && value.len() >= 2 {
        value = &value[1..value.len() - 1];
    }

    if let Some(hex) = value.strip_prefix("0x") {
        u64::from_str_radix(hex, 16).ok()
    } else {
        value.parse::<u64>().ok()
    }
}

fn parse_field_u64(line: &str, field: &str) -> Option<u64> {
    let (name, value) = line.split_once('=')?;
    if name.trim() != field {
        return None;
    }

    parse_toml_u64(value)
}

fn load_slot_bits_from_file(bits: &mut [[u64; FIGHTER_KIND_WORD_COUNT]; ON_ATTACK_OFFSET_COUNT]) {
    if let Err(err) = ensure_slot_file_exists() {
        println!("[on_attack_scan] failed to create {}: {}", slot_path().display(), err);
        return;
    }

    let path = slot_path();
    let data = match fs::read_to_string(&path) {
        Ok(data) => data,
        Err(err) => {
            println!("[on_attack_scan] failed reading {}: {}", path.display(), err);
            return;
        }
    };

    let mut offset = None;
    let mut kind = None;

    for line in data.lines().map(str::trim) {
        if line.starts_with("[[") {
            if let (Some(offset), Some(kind)) = (offset, kind) {
                set_slot_bit(bits, offset, kind);
            }
            offset = None;
            kind = None;
            continue;
        }

        if let Some(value) = parse_field_u64(line, "offset") {
            offset = Some(value as usize);
        } else if let Some(value) = parse_field_u64(line, "kind") {
            kind = Some(value as i32);
        }
    }

    if let (Some(offset), Some(kind)) = (offset, kind) {
        set_slot_bit(bits, offset, kind);
    }
}

fn initialize_slot_cache() {
    let mut bits = [[0; FIGHTER_KIND_WORD_COUNT]; ON_ATTACK_OFFSET_COUNT];
    load_slot_bits_from_file(&mut bits);

    with_slot_cache(|cache| {
        for slot in 0..ON_ATTACK_OFFSET_COUNT {
            for word in 0..FIGHTER_KIND_WORD_COUNT {
                cache.bits[slot][word] |= bits[slot][word];
            }
        }
        cache.initialized = true;
    });
}

fn ensure_slot_cache_initialized() {
    let initialized = with_slot_cache(|cache| cache.initialized);
    if !initialized {
        initialize_slot_cache();
    }
}

fn mark_slot_seen_if_new(slot: usize, kind: i32) -> bool {
    let (word, mask) = match fighter_kind_bit(kind) {
        Some(bit) => bit,
        None => return false,
    };

    ensure_slot_cache_initialized();

    with_slot_cache(|cache| {
        if slot >= ON_ATTACK_OFFSET_COUNT {
            return false;
        }

        if cache.bits[slot][word] & mask != 0 {
            return false;
        }

        cache.bits[slot][word] |= mask;
        true
    })
}

fn append_slot_entry(offset: usize, vtable: u64, kind: i32, fighter: FighterName) {
    if let Err(err) = ensure_slot_file_exists() {
        println!("[on_attack_scan] failed to create {}: {}", slot_path().display(), err);
        return;
    }

    let path = slot_path();
    let mut file = match fs::OpenOptions::new().create(true).append(true).open(&path) {
        Ok(file) => file,
        Err(err) => {
            println!("[on_attack_scan] failed opening {}: {}", path.display(), err);
            return;
        }
    };

    let _ = writeln!(file, "[[slots]]");
    let _ = writeln!(file, "offset = \"0x{:x}\"", offset);
    let _ = writeln!(file, "vtable = \"0x{:x}\"", vtable);
    let _ = writeln!(file, "fighter = \"{}\"", fighter.fighter);
    let _ = writeln!(file, "fighter_kind = \"{}\"", fighter.kind_name);
    let _ = writeln!(file, "kind = 0x{:x}", kind);
    let _ = writeln!(file);
}

unsafe fn log_on_attack_slot(slot: usize, offset: usize, vtable: u64, battle_object: *mut BattleObject) {
    if battle_object.is_null() {
        return;
    }

    let boma = &mut (*(&mut *(battle_object)).module_accessor);
    let kind = boma.kind();
    if !mark_slot_seen_if_new(slot, kind) {
        return;
    }

    if let Some(fighter) = fighter_name_from_kind(kind) {
        append_slot_entry(offset, vtable, kind, fighter);
    }
}

unsafe fn fighter_name_from_kind(kind: i32) -> Option<FighterName> {
    match kind {
        kind if kind == *FIGHTER_KIND_BAYONETTA => Some(FighterName {
            kind_name: "FIGHTER_KIND_BAYONETTA",
            fighter: "bayonetta",
        }),
        kind if kind == *FIGHTER_KIND_BRAVE => Some(FighterName {
            kind_name: "FIGHTER_KIND_BRAVE",
            fighter: "brave",
        }),
        kind if kind == *FIGHTER_KIND_BUDDY => Some(FighterName {
            kind_name: "FIGHTER_KIND_BUDDY",
            fighter: "buddy",
        }),
        kind if kind == *FIGHTER_KIND_CAPTAIN => Some(FighterName {
            kind_name: "FIGHTER_KIND_CAPTAIN",
            fighter: "captain",
        }),
        kind if kind == *FIGHTER_KIND_CHROM => Some(FighterName {
            kind_name: "FIGHTER_KIND_CHROM",
            fighter: "chrom",
        }),
        kind if kind == *FIGHTER_KIND_CLOUD => Some(FighterName {
            kind_name: "FIGHTER_KIND_CLOUD",
            fighter: "cloud",
        }),
        kind if kind == *FIGHTER_KIND_DAISY => Some(FighterName {
            kind_name: "FIGHTER_KIND_DAISY",
            fighter: "daisy",
        }),
        kind if kind == *FIGHTER_KIND_DEDEDE => Some(FighterName {
            kind_name: "FIGHTER_KIND_DEDEDE",
            fighter: "dedede",
        }),
        kind if kind == *FIGHTER_KIND_DEMON => Some(FighterName {
            kind_name: "FIGHTER_KIND_DEMON",
            fighter: "demon",
        }),
        kind if kind == *FIGHTER_KIND_DIDDY => Some(FighterName {
            kind_name: "FIGHTER_KIND_DIDDY",
            fighter: "diddy",
        }),
        kind if kind == *FIGHTER_KIND_DOLLY => Some(FighterName {
            kind_name: "FIGHTER_KIND_DOLLY",
            fighter: "dolly",
        }),
        kind if kind == *FIGHTER_KIND_DONKEY => Some(FighterName {
            kind_name: "FIGHTER_KIND_DONKEY",
            fighter: "donkey",
        }),
        kind if kind == *FIGHTER_KIND_DUCKHUNT => Some(FighterName {
            kind_name: "FIGHTER_KIND_DUCKHUNT",
            fighter: "duckhunt",
        }),
        kind if kind == *FIGHTER_KIND_EDGE => Some(FighterName {
            kind_name: "FIGHTER_KIND_EDGE",
            fighter: "edge",
        }),
        kind if kind == *FIGHTER_KIND_EFLAME => Some(FighterName {
            kind_name: "FIGHTER_KIND_EFLAME",
            fighter: "eflame",
        }),
        kind if kind == *FIGHTER_KIND_ELEMENT => Some(FighterName {
            kind_name: "FIGHTER_KIND_ELEMENT",
            fighter: "element",
        }),
        kind if kind == *FIGHTER_KIND_ELIGHT => Some(FighterName {
            kind_name: "FIGHTER_KIND_ELIGHT",
            fighter: "elight",
        }),
        kind if kind == *FIGHTER_KIND_FALCO => Some(FighterName {
            kind_name: "FIGHTER_KIND_FALCO",
            fighter: "falco",
        }),
        kind if kind == *FIGHTER_KIND_FLAME => Some(FighterName {
            kind_name: "FIGHTER_KIND_FLAME",
            fighter: "flame",
        }),
        kind if kind == *FIGHTER_KIND_FOX => Some(FighterName {
            kind_name: "FIGHTER_KIND_FOX",
            fighter: "fox",
        }),
        kind if kind == *FIGHTER_KIND_FUSHIGISOU => Some(FighterName {
            kind_name: "FIGHTER_KIND_FUSHIGISOU",
            fighter: "fushigisou",
        }),
        kind if kind == *FIGHTER_KIND_GAMEWATCH => Some(FighterName {
            kind_name: "FIGHTER_KIND_GAMEWATCH",
            fighter: "gamewatch",
        }),
        kind if kind == *FIGHTER_KIND_GANON => Some(FighterName {
            kind_name: "FIGHTER_KIND_GANON",
            fighter: "ganon",
        }),
        kind if kind == *FIGHTER_KIND_GAOGAEN => Some(FighterName {
            kind_name: "FIGHTER_KIND_GAOGAEN",
            fighter: "gaogaen",
        }),
        kind if kind == *FIGHTER_KIND_GEKKOUGA => Some(FighterName {
            kind_name: "FIGHTER_KIND_GEKKOUGA",
            fighter: "gekkouga",
        }),
        kind if kind == *FIGHTER_KIND_ICE_CLIMBER => Some(FighterName {
            kind_name: "FIGHTER_KIND_ICE_CLIMBER",
            fighter: "ice_climber",
        }),
        kind if kind == *FIGHTER_KIND_IKE => Some(FighterName {
            kind_name: "FIGHTER_KIND_IKE",
            fighter: "ike",
        }),
        kind if kind == *FIGHTER_KIND_INKLING => Some(FighterName {
            kind_name: "FIGHTER_KIND_INKLING",
            fighter: "inkling",
        }),
        kind if kind == *FIGHTER_KIND_JACK => Some(FighterName {
            kind_name: "FIGHTER_KIND_JACK",
            fighter: "jack",
        }),
        kind if kind == *FIGHTER_KIND_KAMUI => Some(FighterName {
            kind_name: "FIGHTER_KIND_KAMUI",
            fighter: "kamui",
        }),
        kind if kind == *FIGHTER_KIND_KEN => Some(FighterName {
            kind_name: "FIGHTER_KIND_KEN",
            fighter: "ken",
        }),
        kind if kind == *FIGHTER_KIND_KIRBY => Some(FighterName {
            kind_name: "FIGHTER_KIND_KIRBY",
            fighter: "kirby",
        }),
        kind if kind == *FIGHTER_KIND_KOOPA => Some(FighterName {
            kind_name: "FIGHTER_KIND_KOOPA",
            fighter: "koopa",
        }),
        kind if kind == *FIGHTER_KIND_KOOPAG => Some(FighterName {
            kind_name: "FIGHTER_KIND_KOOPAG",
            fighter: "koopag",
        }),
        kind if kind == *FIGHTER_KIND_KOOPAJR => Some(FighterName {
            kind_name: "FIGHTER_KIND_KOOPAJR",
            fighter: "koopajr",
        }),
        kind if kind == *FIGHTER_KIND_KROOL => Some(FighterName {
            kind_name: "FIGHTER_KIND_KROOL",
            fighter: "krool",
        }),
        kind if kind == *FIGHTER_KIND_LIGHT => Some(FighterName {
            kind_name: "FIGHTER_KIND_LIGHT",
            fighter: "light",
        }),
        kind if kind == *FIGHTER_KIND_LINK => Some(FighterName {
            kind_name: "FIGHTER_KIND_LINK",
            fighter: "link",
        }),
        kind if kind == *FIGHTER_KIND_LITTLEMAC => Some(FighterName {
            kind_name: "FIGHTER_KIND_LITTLEMAC",
            fighter: "littlemac",
        }),
        kind if kind == *FIGHTER_KIND_LIZARDON => Some(FighterName {
            kind_name: "FIGHTER_KIND_LIZARDON",
            fighter: "lizardon",
        }),
        kind if kind == *FIGHTER_KIND_LUCARIO => Some(FighterName {
            kind_name: "FIGHTER_KIND_LUCARIO",
            fighter: "lucario",
        }),
        kind if kind == *FIGHTER_KIND_LUCAS => Some(FighterName {
            kind_name: "FIGHTER_KIND_LUCAS",
            fighter: "lucas",
        }),
        kind if kind == *FIGHTER_KIND_LUCINA => Some(FighterName {
            kind_name: "FIGHTER_KIND_LUCINA",
            fighter: "lucina",
        }),
        kind if kind == *FIGHTER_KIND_LUIGI => Some(FighterName {
            kind_name: "FIGHTER_KIND_LUIGI",
            fighter: "luigi",
        }),
        kind if kind == *FIGHTER_KIND_MARIO => Some(FighterName {
            kind_name: "FIGHTER_KIND_MARIO",
            fighter: "mario",
        }),
        kind if kind == *FIGHTER_KIND_MARIOD => Some(FighterName {
            kind_name: "FIGHTER_KIND_MARIOD",
            fighter: "mariod",
        }),
        kind if kind == *FIGHTER_KIND_MARTH => Some(FighterName {
            kind_name: "FIGHTER_KIND_MARTH",
            fighter: "marth",
        }),
        kind if kind == *FIGHTER_KIND_MASTER => Some(FighterName {
            kind_name: "FIGHTER_KIND_MASTER",
            fighter: "master",
        }),
        kind if kind == *FIGHTER_KIND_METAKNIGHT => Some(FighterName {
            kind_name: "FIGHTER_KIND_METAKNIGHT",
            fighter: "metaknight",
        }),
        kind if kind == *FIGHTER_KIND_MEWTWO => Some(FighterName {
            kind_name: "FIGHTER_KIND_MEWTWO",
            fighter: "mewtwo",
        }),
        kind if kind == *FIGHTER_KIND_MIIENEMYF => Some(FighterName {
            kind_name: "FIGHTER_KIND_MIIENEMYF",
            fighter: "miienemyf",
        }),
        kind if kind == *FIGHTER_KIND_MIIENEMYG => Some(FighterName {
            kind_name: "FIGHTER_KIND_MIIENEMYG",
            fighter: "miienemyg",
        }),
        kind if kind == *FIGHTER_KIND_MIIENEMYS => Some(FighterName {
            kind_name: "FIGHTER_KIND_MIIENEMYS",
            fighter: "miienemys",
        }),
        kind if kind == *FIGHTER_KIND_MIIFIGHTER => Some(FighterName {
            kind_name: "FIGHTER_KIND_MIIFIGHTER",
            fighter: "miifighter",
        }),
        kind if kind == *FIGHTER_KIND_MIIGUNNER => Some(FighterName {
            kind_name: "FIGHTER_KIND_MIIGUNNER",
            fighter: "miigunner",
        }),
        kind if kind == *FIGHTER_KIND_MIISWORDSMAN => Some(FighterName {
            kind_name: "FIGHTER_KIND_MIISWORDSMAN",
            fighter: "miiswordsman",
        }),
        kind if kind == *FIGHTER_KIND_MURABITO => Some(FighterName {
            kind_name: "FIGHTER_KIND_MURABITO",
            fighter: "murabito",
        }),
        kind if kind == *FIGHTER_KIND_NANA => Some(FighterName {
            kind_name: "FIGHTER_KIND_NANA",
            fighter: "nana",
        }),
        kind if kind == *FIGHTER_KIND_NESS => Some(FighterName {
            kind_name: "FIGHTER_KIND_NESS",
            fighter: "ness",
        }),
        kind if kind == *FIGHTER_KIND_OTHER_HEAD => Some(FighterName {
            kind_name: "FIGHTER_KIND_OTHER_HEAD",
            fighter: "other_head",
        }),
        kind if kind == *FIGHTER_KIND_OTHER_NUM => Some(FighterName {
            kind_name: "FIGHTER_KIND_OTHER_NUM",
            fighter: "other_num",
        }),
        kind if kind == *FIGHTER_KIND_OTHER_TAIL => Some(FighterName {
            kind_name: "FIGHTER_KIND_OTHER_TAIL",
            fighter: "other_tail",
        }),
        kind if kind == *FIGHTER_KIND_PACKUN => Some(FighterName {
            kind_name: "FIGHTER_KIND_PACKUN",
            fighter: "packun",
        }),
        kind if kind == *FIGHTER_KIND_PACMAN => Some(FighterName {
            kind_name: "FIGHTER_KIND_PACMAN",
            fighter: "pacman",
        }),
        kind if kind == *FIGHTER_KIND_PALUTENA => Some(FighterName {
            kind_name: "FIGHTER_KIND_PALUTENA",
            fighter: "palutena",
        }),
        kind if kind == *FIGHTER_KIND_PEACH => Some(FighterName {
            kind_name: "FIGHTER_KIND_PEACH",
            fighter: "peach",
        }),
        kind if kind == *FIGHTER_KIND_PFUSHIGISOU => Some(FighterName {
            kind_name: "FIGHTER_KIND_PFUSHIGISOU",
            fighter: "pfushigisou",
        }),
        kind if kind == *FIGHTER_KIND_PICHU => Some(FighterName {
            kind_name: "FIGHTER_KIND_PICHU",
            fighter: "pichu",
        }),
        kind if kind == *FIGHTER_KIND_PICKEL => Some(FighterName {
            kind_name: "FIGHTER_KIND_PICKEL",
            fighter: "pickel",
        }),
        kind if kind == *FIGHTER_KIND_PIKACHU => Some(FighterName {
            kind_name: "FIGHTER_KIND_PIKACHU",
            fighter: "pikachu",
        }),
        kind if kind == *FIGHTER_KIND_PIKMIN => Some(FighterName {
            kind_name: "FIGHTER_KIND_PIKMIN",
            fighter: "pikmin",
        }),
        kind if kind == *FIGHTER_KIND_PIT => Some(FighterName {
            kind_name: "FIGHTER_KIND_PIT",
            fighter: "pit",
        }),
        kind if kind == *FIGHTER_KIND_PITB => Some(FighterName {
            kind_name: "FIGHTER_KIND_PITB",
            fighter: "pitb",
        }),
        kind if kind == *FIGHTER_KIND_PLIZARDON => Some(FighterName {
            kind_name: "FIGHTER_KIND_PLIZARDON",
            fighter: "plizardon",
        }),
        kind if kind == *FIGHTER_KIND_POPO => Some(FighterName {
            kind_name: "FIGHTER_KIND_POPO",
            fighter: "popo",
        }),
        kind if kind == *FIGHTER_KIND_PTRAINER => Some(FighterName {
            kind_name: "FIGHTER_KIND_PTRAINER",
            fighter: "ptrainer",
        }),
        kind if kind == *FIGHTER_KIND_PURIN => Some(FighterName {
            kind_name: "FIGHTER_KIND_PURIN",
            fighter: "purin",
        }),
        kind if kind == *FIGHTER_KIND_PZENIGAME => Some(FighterName {
            kind_name: "FIGHTER_KIND_PZENIGAME",
            fighter: "pzenigame",
        }),
        kind if kind == *FIGHTER_KIND_RANDOM => Some(FighterName {
            kind_name: "FIGHTER_KIND_RANDOM",
            fighter: "random",
        }),
        kind if kind == *FIGHTER_KIND_REFLET => Some(FighterName {
            kind_name: "FIGHTER_KIND_REFLET",
            fighter: "reflet",
        }),
        kind if kind == *FIGHTER_KIND_RICHTER => Some(FighterName {
            kind_name: "FIGHTER_KIND_RICHTER",
            fighter: "richter",
        }),
        kind if kind == *FIGHTER_KIND_RIDLEY => Some(FighterName {
            kind_name: "FIGHTER_KIND_RIDLEY",
            fighter: "ridley",
        }),
        kind if kind == *FIGHTER_KIND_ROBOT => Some(FighterName {
            kind_name: "FIGHTER_KIND_ROBOT",
            fighter: "robot",
        }),
        kind if kind == *FIGHTER_KIND_ROCKMAN => Some(FighterName {
            kind_name: "FIGHTER_KIND_ROCKMAN",
            fighter: "rockman",
        }),
        kind if kind == *FIGHTER_KIND_ROSETTA => Some(FighterName {
            kind_name: "FIGHTER_KIND_ROSETTA",
            fighter: "rosetta",
        }),
        kind if kind == *FIGHTER_KIND_ROY => Some(FighterName {
            kind_name: "FIGHTER_KIND_ROY",
            fighter: "roy",
        }),
        kind if kind == *FIGHTER_KIND_RYU => Some(FighterName {
            kind_name: "FIGHTER_KIND_RYU",
            fighter: "ryu",
        }),
        kind if kind == *FIGHTER_KIND_SAMUS => Some(FighterName {
            kind_name: "FIGHTER_KIND_SAMUS",
            fighter: "samus",
        }),
        kind if kind == *FIGHTER_KIND_SAMUSD => Some(FighterName {
            kind_name: "FIGHTER_KIND_SAMUSD",
            fighter: "samusd",
        }),
        kind if kind == *FIGHTER_KIND_SHEIK => Some(FighterName {
            kind_name: "FIGHTER_KIND_SHEIK",
            fighter: "sheik",
        }),
        kind if kind == *FIGHTER_KIND_SHIZUE => Some(FighterName {
            kind_name: "FIGHTER_KIND_SHIZUE",
            fighter: "shizue",
        }),
        kind if kind == *FIGHTER_KIND_SHULK => Some(FighterName {
            kind_name: "FIGHTER_KIND_SHULK",
            fighter: "shulk",
        }),
        kind if kind == *FIGHTER_KIND_SIMON => Some(FighterName {
            kind_name: "FIGHTER_KIND_SIMON",
            fighter: "simon",
        }),
        kind if kind == *FIGHTER_KIND_SNAKE => Some(FighterName {
            kind_name: "FIGHTER_KIND_SNAKE",
            fighter: "snake",
        }),
        kind if kind == *FIGHTER_KIND_SONIC => Some(FighterName {
            kind_name: "FIGHTER_KIND_SONIC",
            fighter: "sonic",
        }),
        kind if kind == *FIGHTER_KIND_SZEROSUIT => Some(FighterName {
            kind_name: "FIGHTER_KIND_SZEROSUIT",
            fighter: "szerosuit",
        }),
        kind if kind == *FIGHTER_KIND_TABLE_EX_START => Some(FighterName {
            kind_name: "FIGHTER_KIND_TABLE_EX_START",
            fighter: "table_ex_start",
        }),
        kind if kind == *FIGHTER_KIND_TABLE_EX_TERM => Some(FighterName {
            kind_name: "FIGHTER_KIND_TABLE_EX_TERM",
            fighter: "table_ex_term",
        }),
        kind if kind == *FIGHTER_KIND_TANTAN => Some(FighterName {
            kind_name: "FIGHTER_KIND_TANTAN",
            fighter: "tantan",
        }),
        kind if kind == *FIGHTER_KIND_TERM => Some(FighterName {
            kind_name: "FIGHTER_KIND_TERM",
            fighter: "term",
        }),
        kind if kind == *FIGHTER_KIND_TOONLINK => Some(FighterName {
            kind_name: "FIGHTER_KIND_TOONLINK",
            fighter: "toonlink",
        }),
        kind if kind == *FIGHTER_KIND_TRAIL => Some(FighterName {
            kind_name: "FIGHTER_KIND_TRAIL",
            fighter: "trail",
        }),
        kind if kind == *FIGHTER_KIND_WARIO => Some(FighterName {
            kind_name: "FIGHTER_KIND_WARIO",
            fighter: "wario",
        }),
        kind if kind == *FIGHTER_KIND_WIIFIT => Some(FighterName {
            kind_name: "FIGHTER_KIND_WIIFIT",
            fighter: "wiifit",
        }),
        kind if kind == *FIGHTER_KIND_WOLF => Some(FighterName {
            kind_name: "FIGHTER_KIND_WOLF",
            fighter: "wolf",
        }),
        kind if kind == *FIGHTER_KIND_YOSHI => Some(FighterName {
            kind_name: "FIGHTER_KIND_YOSHI",
            fighter: "yoshi",
        }),
        kind if kind == *FIGHTER_KIND_YOUNGLINK => Some(FighterName {
            kind_name: "FIGHTER_KIND_YOUNGLINK",
            fighter: "younglink",
        }),
        kind if kind == *FIGHTER_KIND_ZELDA => Some(FighterName {
            kind_name: "FIGHTER_KIND_ZELDA",
            fighter: "zelda",
        }),
        kind if kind == *FIGHTER_KIND_ZENIGAME => Some(FighterName {
            kind_name: "FIGHTER_KIND_ZENIGAME",
            fighter: "zenigame",
        }),
        _ => None,
    }
}

pub fn install() {
    initialize_slot_cache();

    skyline::install_hooks!(
        on_attack_log_68d7e0,
        on_attack_log_81ec30,
        // on_attack_log_854520, // brave
        on_attack_log_892af0,
        on_attack_log_8b8b90,
        on_attack_log_8dc4f0,
        on_attack_log_90d630,
        // on_attack_log_932f50, // demon
        on_attack_log_9567c0,
        on_attack_log_9720a0,
        on_attack_log_994480,
        on_attack_log_9a5070,
        on_attack_log_9df7b0,
        on_attack_log_a0cec0,
        on_attack_log_a29ab0,
        on_attack_log_a47bf0,
        on_attack_log_a64ce0,
        on_attack_log_a82660,
        on_attack_log_aa6540,
        on_attack_log_ab9970,
        on_attack_log_adb1a0,
        // on_attack_log_af9350, // ike
        on_attack_log_b33d30,
        on_attack_log_b5e240,
        on_attack_log_b98cf0,
        on_attack_log_c08430,
        on_attack_log_c29220,
        // on_attack_log_c456a0, // littlemac
        on_attack_log_c73580,
        on_attack_log_ca13a0,
        on_attack_log_cd9ea0,
        // on_attack_log_cea640, // master
        on_attack_log_d13020,
        on_attack_log_d29f90,
        on_attack_log_d575b0,
        on_attack_log_d9aa90,
        on_attack_log_df0370,
        on_attack_log_e2a690,
        on_attack_log_e60c30,
        on_attack_log_f96420,
        on_attack_log_f0acc0,
        on_attack_log_f2ae00,
        on_attack_log_f6f210,
        on_attack_log_f93df0,
        on_attack_log_fdf990,
        on_attack_log_1006730,
        on_attack_log_1044590,
        on_attack_log_105cf60,
        on_attack_log_10bbd90,
        on_attack_log_10d6ca0,
        on_attack_log_1121600,
        on_attack_log_116dbb0,
        on_attack_log_1195670,
        on_attack_log_11d5a00,
        on_attack_log_11f5380,
        on_attack_log_122a360,
        on_attack_log_12689c0,
        on_attack_log_1287320,
        on_attack_log_12ae760,
        on_attack_log_12dc040,
        on_attack_log_130eff0,
    );
}
